stages:
  - test
  
job_build:
  stage: test
  script:
    - echo "Running tests"
    - apt-get update -qy
    - apt-get install -y python-dev-is-python3 python3-pip
    - pip install -r requirements.txt --break-system-packages
    - python3 test.py

