stages:
  - build
  - test
  
before_script:
  - apt-get -y install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin

job_build:
  stage: build
  script:
    - echo "Building the project"
    - docker compose up --build

job_test:
  stage: test
  script:
    - echo "Running tests"
    - echo "no test scripts are setup currently"
